name: py3.12, py.3.13

on:
  push:
    branches: [ main ] 
jobs:
  tox_test:
    name: Tox test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tox tests
        id: test
        uses: fedora-python/tox-github-action@main
        with:
          tox_env: py313,py312
          dnf_install: poetry
